services:
  redis:
    image: redis:latest
    container_name: avito_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    volumes:
      - redis_data:/data
    networks:
      - avito_network

  postgres:
    image: postgres:16-alpine
    container_name: avito_postgres
    environment:
      POSTGRES_DB: avito_moderation
      POSTGRES_USER: vagrigorevaaa
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - avito_network

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: avito_redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - avito_network

  console:
    image: redpandadata/console:latest
    container_name: avito_console
    environment:
      KAFKA_BROKERS: redpanda:29092
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
    networks:
      - avito_network

  prometheus:
    image: prom/prometheus:latest
    container_name: avito_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - avito_network

  grafana:
    image: grafana/grafana:latest
    container_name: avito_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - avito_network

networks:
  avito_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
